### ISSUE TITLE
Suggest you set up https://docs.github.com/en/discussions for this repo

### ISSUE THREAD

**Issue by PaulFWatts** [WebstoneHQ/platform#12]
After having done your recent full-stack course I'm keen to see what you come up with next!
This sounds like an exciting project, and I suggest Discussions will facilitate collaboration.
All the best with it.

**Comment by mikenikles** [comment]
Hey Paul, that's a great idea! Discussions is enabled :smiley:. Thanks for the suggestion.

Also, thanks for taking my course. Do you have any feedback at all I could learn from?

**Comment by mikenikles** [comment]
Closing this since Discussions are now enabled and we also have a [Discord server](https://discord.gg/dt583vtkeZ).
